port=53
listen-address=10.77.0.1
bind-interfaces
no-resolv
no-hosts
no-poll
cache-size=0
pid-file=
log-facility=-
user=retro
group=retro
local=/#/
hostsdir=/srv/site-dns
host-record=ns.retro.home.arpa,10.77.0.1
host-record=www.retro.home.arpa,10.77.0.1
host-record=files.retro.home.arpa,10.77.0.1
host-record=retro.net,10.77.0.1
host-record=www.retro.net,10.77.0.1
host-record=files.retro.net,10.77.0.1
host-record=members.retro.net,10.77.0.1
